version: '3.8'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-12.5}
    container_name: ${POSTGRES_NAME:-requisition-database}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
    name: requisition-volume

networks:
  app-network:
    name: requisition-network
